erDiagram
main__option_chain {
  date date
  string act_symbol
  date expiration
  float strike
  string call_put
  float bid
  float ask
  float vol
  float delta
  float gamma
  float theta
  float vega
  float rho
}
main__volatility_history {
  date date
  string act_symbol
  float hv_current
  float hv_week_ago
  float hv_month_ago
  float hv_year_high
  date hv_year_high_date
  float hv_year_low
  date hv_year_low_date
  float iv_current
  float iv_week_ago
  float iv_month_ago
  float iv_year_high
  date iv_year_high_date
  float iv_year_low
  date iv_year_low_date
}